### ISSUE TITLE
BUG: Sending encoded parameters via request.post in report_client.py

### ISSUE THREAD

**Issue by ghost** [GrowthPath/zoho_analytics_connector#2]
The getAsPayLoad function on line 2051 in the report_client.py module, encodes the payload on line 2064 using urllib.parse.encode That payload is later used as a parameter in the request.post function on line 131. "request.post" automatically encodes any data parameters sent in a post statement, so the parameters are ignored in the post function. This affects ZOHO_CRITERIA that are passed and causes functions such as "exportData" to return the entire table instead of applying the filter criteria. By removing urllib.parse.urlencode on line 2064, the filter criteria worked in "exportData"

**Comment by timrichardson** [comment]
can you send me the filter criteria you used? I need to be careful changing such a lowlevel function (report_client.py is code from zoho)

**Comment by ghost** [comment]
I am filtering on a date field in the target Zoho table. The parameter passed is ("DateField" = 'yyyy-mm-dd'). In the exportData function, this looks like 

query = '("' + FieldName +'" =' + "'yyyy-mm-dd')"
rc.exportData(uri,"CSV",fileobj, query).

I am referencing the following from the Zoho api - https://www.zoho.com/analytics/api/#applying-filter-criteria

**Comment by timrichardson** [comment]
I have added  a test case for this and changed getAsPayLoad as you suggest. My tests are all passing so I will try it with something more substantial. I have pushed these changes to git hub.

**Comment by timrichardson** [comment]
closed with v 1.1.2
